// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxnstmzmjegajxygsczo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4bnN0bXptamVnYWp4eWdzY3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzUyODIsImV4cCI6MjA2MDMxMTI4Mn0.yyll0nzJ30A2boR71Vy5VTQffqhg3-cAgY1YgFS919E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);